# Nova
nova::db::mysql::user: nova
nova::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
nova::db::mysql::dbname: nova
nova::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

# Glance
glance::db::mysql::user: glance
glance::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
glance::db::mysql::dbname: glance
glance::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

# Keystone
keystone::db::mysql::user: keystone
keystone::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
keystone::db::mysql::dbname: keystone
keystone::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

# Neutron
neutron::db::mysql::user: neutron
neutron::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
neutron::db::mysql::dbname: ovs_neutron
neutron::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

# Cinder
cinder::db::mysql::user: cinder
cinder::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
cinder::db::mysql::dbname: cinder
cinder::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

# Heat
heat::db::mysql::user: heat
heat::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
heat::db::mysql::dbname: heat
heat::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

# Ceilometer
ceilometer::db::mysql::user: ceilometer
ceilometer::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
ceilometer::db::mysql::dbname: ceilometer
ceilometer::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"
