heat_template_version: 2015-04-30
description: 'Post-Puppet Config for Compute Nodes'

parameters:
  servers:
    type: json
  update_identifier:
    type: string

resources:

  ComputePostPuppetYumUpdateConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: yum_update_post.sh}

  ComputePostPuppetYumUpdateDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ComputePostPuppetYumUpdateConfig}
      input_values:
        update_identifier: {get_param: update_identifier}
