heat_template_version: 2015-04-30
description: 'OpenStack cinder storage post deployment for Puppet'

parameters:
  ConfigDebug:
    default: false
    description: Whether to run config management (e.g. Puppet) in debug mode.
    type: boolean
  servers:
    type: json
  NodeConfigIdentifiers:
     type: json
     description: Value which changes if the node configuration may need to be re-applied

resources:

  VolumeArtifactsConfig:
    type: deploy-artifacts.yaml

  VolumeArtifactsDeploy:
    type: OS::Heat::StructuredDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: VolumeArtifactsConfig}
      input_values:
        update_identifier: {get_param: NodeConfigIdentifiers}

  VolumePuppetConfig:
    type: OS::Heat::SoftwareConfig
    depends_on: VolumeArtifactsDeploy
    properties:
      group: puppet
      options:
        enable_debug: {get_param: ConfigDebug}
      outputs:
      - name: result
      config:
        get_file: manifests/overcloud_volume.pp

  VolumeDeployment_Step1:
    type: OS::Heat::StructuredDeployments
    properties:
      name: VolumeDeployment_Step1
      servers:  {get_param: servers}
      config: {get_resource: VolumePuppetConfig}

  # Note, this should come last, so use depends_on to ensure
  # this is created after any other resources.
  ExtraConfig:
    depends_on: VolumeDeployment_Step1
    type: OS::TripleO::NodeExtraConfigPost
    properties:
        servers: {get_param: servers}
