heat_template_version: 2015-04-30

description: >
  A software config which runs manifests/overcloud_controller.pp

parameters:
  ConfigDebug:
    default: false
    description: Whether to run config management (e.g. Puppet) in debug mode.
    type: boolean

resources:

  ControllerPuppetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: puppet
      options:
        enable_debug: {get_param: ConfigDebug}
        enable_hiera: True
        enable_facter: False
      outputs:
      - name: result
      config:
        get_file: manifests/overcloud_controller.pp

outputs:
  OS::stack_id:
    description: The software config which runs overcloud_controller.pp
    value: {get_resource: ControllerPuppetConfigImpl}
