# A Heat environment file which can be used to enable a
# a Cinder  eqlx backen, configured via puppet
resource_registry:
  OS::TripleO::ControllerExtraConfigPre: ../puppet/extraconfig/pre_deploy/controller/cinder-eqlx.yaml

parameter_defaults:
  CinderEnableEqlxBackend: true
  CinderEqlxBackendName: 'tripleo_eqlx'
  CinderEqlxSanIp: ''
  CinderEqlxSanLogin: ''
  CinderEqlxSanPassword: ''
  CinderEqlxSanThinProvision: true
  CinderEqlxGroupname: 'group-0'
  CinderEqlxPool: 'default'
  CinderEqlxChapLogin: ''
  CinderEqlxChapPassword: ''
  CinderEqlxUseChap: false
