# A Heat environment file which can be used to enable a
# a Cinder  Dell Storage Center ISCSI backend, configured via puppet
resource_registry:
  OS::TripleO::ControllerExtraConfigPre: ../puppet/extraconfig/pre_deploy/controller/cinder-dellsc.yaml

parameter_defaults:
  CinderEnableDellScBackend: true
  CinderDellScBackendName: 'tripleo_dellsc'
  CinderDellScSanIp: ''
  CinderDellScSanLogin: 'Admin'
  CinderDellScSanPassword: ''
  CinderDellScSsn: '64702'
  CinderDellScIscsiIpAddress: ''
  CinderDellScIscsiPort: '3260'
  CinderDellScApiPort: '3033'
  CinderDellScServerFolder: 'dellsc_server'
  CinderDellScVolumeFolder: 'dellsc_volume'
