#!/bin/bash
# Install pcs if it is available
# dib-lint: disable=sete

if [ "${DIB_DEBUG_TRACE:-1}" -gt 0 ]; then
    set -x
fi
set -u
set -o pipefail

HAS_PACKAGE=$(yum list | grep pcs)
if [ -n "$HAS_PACKAGE" ]; then
    install-packages pcs
fi
