heat_template_version: 2015-04-30

description: Configure hieradata for Big Switch agents on compute node

parameters:
  server:
    description: ID of the controller node to apply this config to
    type: string
  NeutronBigswitchAgentEnabled:
    description: The state of the neutron-bsn-agent service.
    type: boolean
    default: false
  NeutronBigswitchLLDPEnabled:
    description: The state of the neutron-bsn-lldp service.
    type: boolean
    default: true


resources:
  NeutronBigswitchConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hiera:
          datafiles:
            neutron_bigswitch_data:
              mapped_data:
                neutron::agents::bigswitch::agent_enabled: {get_input: neutron_enable_bigswitch_agent}
                neutron::agents::bigswitch::lldp_enabled: {get_input: neutron_enable_bigswitch_lldp}

  NeutronBigswitchDeployment:
    type: OS::Heat::StructuredDeployment
    properties:
      name: NeutronBigswitchDeployment
      config: {get_resource: NeutronBigswitchConfig}
      server: {get_param: server}
      input_values:
        neutron_enable_bigswitch_agent: {get_param: NeutronBigswitchAgentEnabled}
        neutron_enable_bigswitch_lldp: {get_param: NeutronBigswitchLLDPEnabled}

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger puppet apply on changes
    value: {get_attr: [NeutronBigswitchDeployment, deploy_stdout]}
