heat_template_version: 2014-10-16
description: 'Extra Pre-Deployment Config, multiple'
parameters:
  server:
    type: string

resources:

  CinderNetappConfig:
    type: cinder-netapp.yaml
    properties:
        server: {get_param: server}

  # Note depends_on may be used for serialization if ordering is important
  OtherConfig:
    type: other.yaml
    properties:
        server: {get_param: server}
