heat_template_version: 2015-04-30

description: >
  Storage management network. Storage replication, etc.

parameters:
  # the defaults here work for static IP assignment (IPAM) only
  StorageMgmtNetCidr:
    default: '172.16.3.0/24'
    description: Cidr for the storage management network.
    type: string
  StorageMgmtNetValueSpecs:
    default: {'provider:physical_network': 'storage_mgmt', 'provider:network_type': 'flat'}
    description: Value specs for the storage_mgmt network.
    type: json
  StorageMgmtNetAdminStateUp:
    default: false
    description: This admin state of of the network.
    type: boolean
  StorageMgmtNetEnableDHCP:
    default: false
    description: Whether to enable DHCP on the associated subnet.
    type: boolean
  StorageMgmtNetShared:
    default: false
    description: Whether this network is shared across all tenants.
    type: boolean
  StorageMgmtNetName:
    default: storage_mgmt
    description: The name of the Storage management network.
    type: string
  StorageMgmtSubnetName:
    default: storage_mgmt_subnet
    description: The name of the Storage management subnet in Neutron.
    type: string
  StorageMgmtAllocationPools:
    default: [{'start': '172.16.3.4', 'end': '172.16.3.250'}]
    description: Ip allocation pool range for the storage mgmt network.
    type: json

resources:
  StorageMgmtNetwork:
    type: OS::Neutron::Net
    properties:
      admin_state_up: {get_param: StorageMgmtNetAdminStateUp}
      name: {get_param: StorageMgmtNetName}
      shared: {get_param: StorageMgmtNetShared}
      value_specs: {get_param: StorageMgmtNetValueSpecs}

  StorageMgmtSubnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: {get_param: StorageMgmtNetCidr}
      enable_dhcp: {get_param: StorageMgmtNetEnableDHCP}
      name: {get_param: StorageMgmtSubnetName}
      network: {get_resource: StorageMgmtNetwork}
      allocation_pools: {get_param: StorageMgmtAllocationPools}

outputs:
  OS::stack_id:
    description: Neutron storage management network
    value: {get_resource: StorageMgmtNetwork}
