#! /bin/bash

set -ex

if [ "$ACTION" == "install" ] ; then
    /usr/bin/install.sh
    exit 0
fi

if [ "$ACTION" == "uninstall" ] ; then
    /usr/bin/uninstall.sh
    exit 0
fi

if [ "$ADEBUG" != "" ] ; then
    if [ "$ADEBUG" == "1" ] ; then
       set -ex
    fi
else
    set -ex
fi

export LC_ALL=C

if [ ! -f /etc/ssh/ssh_host_dsa_key ] ; then
     ssh-keygen -t dsa -q -N "" -f /etc/ssh/ssh_host_dsa_key
     ssh-keygen -t rsa -q -N "" -f /etc/ssh/ssh_host_rsa_key
     ssh-keygen -t ecdsa -q -N "" -f /etc/ssh/ssh_host_ecdsa_key
     ssh-keygen -t ed25519 -q -N "" -f /etc/ssh/ssh_host_ed25519_key
fi

if [ "$MY_IP" != "" ] ; then
   echo -e "DEVICE=br0\nTYPE=Bridge\nBOOTPROTO=none\nONBOOT=yes\nNAME=br0\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-br0
   echo -e "IPADDR=${MY_IP}\nPREFIX=24" >> /etc/sysconfig/network-scripts/ifcfg-br0
   if [ "$MY_GATEWAY" != "" ] ; then
     echo -e "DEFROUTE=yes\nPEERDNS=yes\nPEERROUTES=yes\nGATEWAY=${MY_GATEWAY}" >> /etc/sysconfig/network-scripts/ifcfg-br0
   fi
   if [ "$MY_PREFIX" != "" ] ; then
     sed -i "s/PREFIX=.*/PREFIX=$MY_PREFIX/g" /etc/sysconfig/network-scripts/ifcfg-br0
   fi
fi

if [ "$MY_IP1" != "" ] ; then
   echo -e "DEVICE=br1\nTYPE=Bridge\nBOOTPROTO=none\nONBOOT=yes\nNAME=br1\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-br1
   echo -e "IPADDR=${MY_IP1}\nPREFIX=24" >> /etc/sysconfig/network-scripts/ifcfg-br1
   if [ "$MY_GATEWAY1" != "" ] ; then
     echo -e "DEFROUTE=yes\nPEERDNS=yes\nPEERROUTES=yes\nGATEWAY=${MY_GATEWAY1}" >> /etc/sysconfig/network-scripts/ifcfg-br1
   fi
   if [ "$MY_PREFIX1" != "" ] ; then
     sed -i "s/PREFIX=.*/PREFIX=$MY_PREFIX1/g" /etc/sysconfig/network-scripts/ifcfg-br1
   fi
fi

if [ "$MY_IP2" != "" ] ; then
   echo -e "DEVICE=br2\nTYPE=Bridge\nBOOTPROTO=none\nONBOOT=yes\nNAME=br2\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-br2
   echo -e "IPADDR=${MY_IP2}\nPREFIX=24" >> /etc/sysconfig/network-scripts/ifcfg-br2
   if [ "$MY_GATEWAY2" != "" ] ; then
     echo -e "DEFROUTE=yes\nPEERDNS=yes\nPEERROUTES=yes\nGATEWAY=${MY_GATEWAY2}" >> /etc/sysconfig/network-scripts/ifcfg-br2
   fi
   if [ "$MY_PREFIX2" != "" ] ; then
     sed -i "s/PREFIX=.*/PREFIX=$MY_PREFIX2/g" /etc/sysconfig/network-scripts/ifcfg-br2
   fi
fi

if [ "$MY_IP3" != "" ] ; then
   echo -e "DEVICE=br3\nTYPE=Bridge\nBOOTPROTO=none\nONBOOT=yes\nNAME=br3\nONBOOT=yes" > /etc/sysconfig/network-scripts/ifcfg-br3
   echo -e "IPADDR=${MY_IP3}\nPREFIX=24" >> /etc/sysconfig/network-scripts/ifcfg-br3
   if [ "$MY_GATEWAY3" != "" ] ; then
     echo -e "DEFROUTE=yes\nPEERDNS=yes\nPEERROUTES=yes\nGATEWAY=${MY_GATEWAY3}" >> /etc/sysconfig/network-scripts/ifcfg-br3
   fi
   if [ "$MY_PREFIX3" != "" ] ; then
     sed -i "s/PREFIX=.*/PREFIX=$MY_PREFIX3/g" /etc/sysconfig/network-scripts/ifcfg-br3
   fi
fi


systemctl restart messagebus || true
systemctl restart sshd || true
systemctl restart iptables || true
systemctl restart libvirtd || true

HOSTNAME_FQDN=$(hostname)
HOSTNAME_SHORT=${HOSTNAME_FQDN%%.*}
DOMAIN=${HOSTNAME_FQDN#*.}

export DOMAIN
export HOSTNAME_FQDN
export HOSTNAME_SHORT

if [ "$BRCTL_SUBNET_PREFIX" == "" ] ; then
     BRCTL_SUBNET_PREFIX="192.170"
fi

/usr/sbin/sysctl -p 

nohup /usr/sbin/phys_wait_en0.sh &

if [ -t 0 ] ; then
   echo 'Starting interactive shell.'
   export LC_ALL=C
   /bin/bash
else
   echo 'Go loop.'
   export LC_ALL=C
   while true ;
   do
     /bin/bash
     sleep 10 & wait $!
   done
fi

