heat_template_version: 2015-04-30

description: >
  Internal API network. Used for most APIs, Database, RPC.

parameters:
  # the defaults here work for static IP assignment (IPAM) only
  InternalApiNetCidr:
    default: '172.16.2.0/24'
    description: Cidr for the internal API network.
    type: string
  InternalApiNetValueSpecs:
    default: {'provider:physical_network': 'internal_api', 'provider:network_type': 'flat'}
    description: Value specs for the internal API network.
    type: json
  InternalApiNetAdminStateUp:
    default: false
    description: This admin state of the network.
    type: boolean
  InternalApiNetEnableDHCP:
    default: false
    description: Whether to enable DHCP on the associated subnet.
    type: boolean
  InternalApiNetShared:
    default: false
    description: Whether this network is shared across all tenants.
    type: boolean
  InternalApiNetName:
    default: internal_api
    description: The name of the internal API network.
    type: string
  InternalApiSubnetName:
    default: internal_api_subnet
    description: The name of the internal API subnet in Neutron.
    type: string
  InternalApiAllocationPools:
    default: [{'start': '172.16.2.4', 'end': '172.16.2.250'}]
    description: Ip allocation pool range for the internal API network.
    type: json

resources:
  InternalApiNetwork:
    type: OS::Neutron::Net
    properties:
      admin_state_up: {get_param: InternalApiNetAdminStateUp}
      name: {get_param: InternalApiNetName}
      shared: {get_param: InternalApiNetShared}
      value_specs: {get_param: InternalApiNetValueSpecs}

  InternalApiSubnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: {get_param: InternalApiNetCidr}
      enable_dhcp: {get_param: InternalApiNetEnableDHCP}
      name: {get_param: InternalApiSubnetName}
      network: {get_resource: InternalApiNetwork}
      allocation_pools: {get_param: InternalApiAllocationPools}

outputs:
  OS::stack_id:
    description: Neutron internal network
    value: {get_resource: InternalApiNetwork}
