#! /bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

set -ex

if [ "$ACTION" == "install" ] ; then
    /usr/bin/install.sh
    exit 0
fi

if [ "$ACTION" == "uninstall" ] ; then
    /usr/bin/uninstall.sh
    exit 0
fi

if [ "$ADEBUG" != "" ] ; then
    if [ "$ADEBUG" == "1" ] ; then
       set -ex
    fi
else
    set -ex
fi

export LC_ALL=C

if [ ! -f /etc/ssh/ssh_host_dsa_key ] ; then
     ssh-keygen -t dsa -q -N "" -f /etc/ssh/ssh_host_dsa_key
     ssh-keygen -t rsa -q -N "" -f /etc/ssh/ssh_host_rsa_key
     ssh-keygen -t ecdsa -q -N "" -f /etc/ssh/ssh_host_ecdsa_key
     ssh-keygen -t ed25519 -q -N "" -f /etc/ssh/ssh_host_ed25519_key
fi

mkdir -p /var/run/netns

if [ "$MY_IP" != "" ] ; then
    sed -i "s/IPADDR=.*/IPADDR=$MY_IP/g" /etc/sysconfig/network-scripts/ifcfg-br0
fi
if [ "$MY_GATEWAY" != "" ] ; then
    sed -i "s/GATEWAY=.*/GATEWAY=$MY_GATEWAY/g" /etc/sysconfig/network-scripts/ifcfg-br0
fi
if [ "$MY_PREFIX" != "" ] ; then
    sed -i "s/PREFIX=.*/PREFIX=$MY_PREFIX/g" /etc/sysconfig/network-scripts/ifcfg-br0
fi

systemctl restart messagebus || true
systemctl restart sshd || true
systemctl restart iptables || true
systemctl restart libvirtd || true

HOSTNAME_FQDN=$(hostname)
HOSTNAME_SHORT=${HOSTNAME_FQDN%%.*}
DOMAIN=${HOSTNAME_FQDN#*.}

export DOMAIN
export HOSTNAME_FQDN
export HOSTNAME_SHORT

if [ "$BRCTL_SUBNET_PREFIX" == "" ] ; then
     BRCTL_SUBNET_PREFIX="192.170"
fi

myloop=$(losetup -a | grep "mydata-${NAME}.disk" | tail -n 1 | awk -F ':' '{ print $1;}')
if [ "$myloop" != "" ] ; then
    echo $myloop > /myloop
    losetup -d $myloop
fi

mkdir -p /home/stack/.ssh 
alias cp=cp
cp -af /root/.ssh/* /home/stack/.ssh/
chown -R stack:stack /home/stack/.ssh

sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT local_ip $BRCTL_SUBNET_PREFIX.11.1/16"
sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT undercloud_public_vip  $BRCTL_SUBNET_PREFIX.11.10"
sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT undercloud_admin_vip $BRCTL_SUBNET_PREFIX.11.11"
sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT masquerade_network $BRCTL_SUBNET_PREFIX.0.0/16"
sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT dhcp_start $BRCTL_SUBNET_PREFIX.11.20"
sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT dhcp_end $BRCTL_SUBNET_PREFIX.11.120"
sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT network_cidr $BRCTL_SUBNET_PREFIX.0.0/16"
sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT network_gateway $BRCTL_SUBNET_PREFIX.0.1"
sudo -u stack /usr/bin/bash -c  "openstack-config --set ~/undercloud.conf DEFAULT inspection_iprange  $BRCTL_SUBNET_PREFIX.11.150,$BRCTL_SUBNET_PREFIX.11.180"

nohup /usr/sbin/phys_wait_en0.sh &

if [ -t 0 ] ; then
   echo 'Starting interactive shell.'
   export LC_ALL=C
   /bin/bash
else
   echo 'Go loop.'
   export LC_ALL=C
   while true ;
   do
     /bin/bash
     sleep 10 & wait $!
   done
fi

