heat_template_version: 2015-04-30

description: >
  Software Config to drive validations that occur on all nodes.
  Note, you need the heat-config-script element built into your
  images, due to the script group below.

parameters:
  PingTestIps:
    default: ''
    description: A string containing a space separated list of IP addresses used to ping test each available network interface.
    type: string

resources:
  AllNodesValidationsImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: ping_test_ips
          default: {get_param: PingTestIps}
      config: {get_file: ./validation-scripts/all-nodes.sh}

outputs:
  OS::stack_id:
    description: The ID of the AllNodesValidationsImpl resource.
    value: {get_resource: AllNodesValidationsImpl}
