resources:
  undercloudNovaConfig:
    type: OS::Heat::StructuredConfig
    properties:
      config:
        nova:
          compute_hostname: undercloud
          compute_driver: {get_param: NovaComputeDriver}
          compute_manager: {get_param: NovaComputeManager}
          scheduler_host_manager: {get_param: NovaSchedulerHostManager}
          db: {list_join: ['', ['mysql://nova:', {get_param: NovaPassword}, '@localhost/nova']]}
          default_ephemeral_format: ext4
          host: 127.0.0.1
          metadata-proxy: false
          tuning:
            ram_allocation_ratio: 1.0
            reserved_host_memory_mb: 0
          baremetal:
            arch: {get_input: nova_arch}
            db: {list_join: ['', ['mysql://nova:', {get_param: NovaPassword}, '@localhost/nova_bm']]}
            power_manager: {get_input: power_manager}
            pxe_deploy_timeout: {get_input: pxe_deploy_timeout}
          service-password: {get_input: nova_service_password}
