resources:
  undercloudNovaConfig:
    type: OS::Heat::StructuredConfig
    properties:
      config:
        nova:
          compute_hostname: undercloud
          compute_driver: {get_param: NovaComputeDriver}
          compute_manager: {get_param: NovaComputeManager}
          scheduler_host_manager: {get_param: NovaSchedulerHostManager}
          db: {list_join: ['', ['mysql://nova:', {get_param: NovaPassword}, '@localhost/nova']]}
          debug: {get_param: Debug}
          default_ephemeral_format: ext4
          host: 127.0.0.1
          metadata-proxy: false
          tuning:
            ram_allocation_ratio: 1.0
            reserved_host_memory_mb: 0
          service-password: {get_input: nova_service_password}
  undercloudIronicConfig:
    type: OS::Heat::StructuredConfig
    properties:
      config:
        ironic:
          db: {list_join: ['', ['mysql://ironic:', {get_param: IronicPassword}, '@localhost/ironic']]}
          service-password: {get_input: ironic_service_password}
          virtual_power_ssh_key: {get_input: virtual_power_ssh_key}
