heat_template_version: 2015-04-30

description: >
  Configure hieradata for service -> virtual IP mappings.

resources:
  VipConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      # by default does nothing

outputs:
  OS::stack_id:
    description: The VipConfigImpl resource.
    value: {get_resource: VipConfigImpl}
