heat_template_version: 2015-04-30

description: >
  A software config which runs manifests/overcloud_controller_pacemaker.pp

resources:

  ControllerPuppetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: puppet
      options:
        enable_hiera: True
        enable_facter: False
      outputs:
      - name: result
      config:
        get_file: manifests/overcloud_controller_pacemaker.pp

outputs:
  OS::stack_id:
    description: The software config which runs overcloud_controller_pacemaker.pp
    value: {get_resource: ControllerPuppetConfigImpl}
