heat_template_version: 2014-10-16

parameters:
  DockerAgentImage:
    type: string
    default: heat-docker-agents
  DockerNamespace:
    type: string
    default: kollaglue
  DockerNamespaceIsRegistry:
    type: boolean
    default: false

resources:

  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: install_docker_agents}

  install_docker_agents:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          params:
            $agent_image:
              list_join:
              - '/'
              - [ {get_param: DockerNamespace}, {get_param: DockerAgentImage} ]
            $docker_registry: {get_param: DockerNamespace}
            $docker_namespace_is_registry: {get_param: DockerNamespaceIsRegistry}
          template: {get_file: ./start_docker_agents.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
