heat_template_version: 2014-10-16
description: 'Pre-Puppet Config for Pacemaker deployments'

parameters:
  servers:
    type: json
  input_values:
     type: json
     description: input values for the software deployments

resources:

  ControllerPrePuppetMaintenanceModeConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        get_file: pacemaker_maintenance_mode.sh

  ControllerPrePuppetMaintenanceModeDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ControllerPrePuppetMaintenanceModeConfig}
      input_values: {get_param: input_values}
