heat_template_version: 2015-04-30

description: >
  This is a default no-op template which can be passed to the
  OS::Nova::Server resources. This template can be replaced with
  a different implementation via the resource registry, such that
  deployers may customize their configuration.

parameters:
  server:    # Here for compatibility with controller.yaml
    description: ID of the controller node to apply this config to
    type: string

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger puppet apply on changes
    value: 'Root CA cert injection not enabled.'
