heat_template_version: 2015-04-30

description: >
  This is a default no-op template. This defines the parameters that
  need to be passed in order to have TLS enabled in the controller
  nodes. This template can be replaced with a different
  implementation via the resource registry, such that deployers
  may customize their configuration.

parameters:
  DeployedSSLCertificatePath:
    default: ''
    description: >
        The filepath of the certificate as it will be stored in the controller.
    type: string
  NodeIndex: # Here for compatibility with puppet/controller.yaml
    default: 0
    type: number
  server:    # Here for compatibility with puppet/controller.yaml
    description: ID of the controller node to apply this config to
    type: string

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger puppet apply on changes
    value: 'TLS not enabled.'
  deployed_ssl_certificate_path:
    value: ''
  key_modulus_md5:
    description: Key SSL Modulus
    value: ''
  cert_modulus_md5:
    description: Certificate SSL Modulus
    value: ''
