heat_template_version: 2015-04-30

parameters:
  ControlPlaneIp:
    default: ''
    type: string
  ExternalIp:
    default: ''
    type: string
  ExternalIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  InternalApiIp:
    default: ''
    type: string
  InternalApiIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  StorageIp:
    default: ''
    type: string
  StorageIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  StorageMgmtIp:
    default: ''
    type: string
  StorageMgmtIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  TenantIp:
    default: ''
    type: string
  TenantIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6

outputs:
  net_ip_map:
    description: >
      A Hash containing a mapping of network names to assigned IPs
      for a specific machine.
    value:
      ctlplane: {get_param: ControlPlaneIp}
      external: {get_param: ExternalIp}
      internal_api: {get_param: InternalApiIp}
      storage: {get_param: StorageIp}
      storage_mgmt: {get_param: StorageMgmtIp}
      tenant: {get_param: TenantIp}
  net_ip_uri_map:
    description: >
      A Hash containing a mapping of netowrk names to assigned IPs for a
      specific machine with brackets around IPv6 addresses for use in URLs.
    value:
      ctlplane: {get_param: ControlPlaneIp}
      external: {get_param: ExternalIpUri}
      internal_api: {get_param: InternalApiIpUri}
      storage: {get_param: StorageIpUri}
      storage_mgmt: {get_param: StorageMgmtIpUri}
      tenant: {get_param: TenantIpUri}
