heat_template_version: 2015-04-30

parameters:
  ControlPlaneIp:
    default: ''
    type: string
  ExternalIpSubnet:
    default: ''
    type: string
  InternalApiIpSubnet:
    default: ''
    type: string
  StorageIpSubnet:
    default: ''
    type: string
  StorageMgmtIpSubnet:
    default: ''
    type: string
  TenantIpSubnet:
    default: ''
    type: string
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string

outputs:
  net_ip_subnet_map:
    description: >
      A Hash containing a mapping of network names to assigned
      IP/subnet mappings.
    value:
      ctlplane:
        list_join:
          - ''
          - - {get_param: ControlPlaneIp}
            - '/'
            - {get_param: ControlPlaneSubnetCidr}
      external: {get_param: ExternalIpSubnet}
      internal_api: {get_param: InternalApiIpSubnet}
      storage: {get_param: StorageIpSubnet}
      storage_mgmt: {get_param: StorageMgmtIpSubnet}
      tenant: {get_param: TenantIpSubnet}
