heat_template_version: 2015-04-30

description: >
  Returns the control plane port (provisioning network) as the ip_address.

parameters:
  ServiceName: # Here for compatibility with from_service.yaml
    description: Name of the service to lookup
    default: ''
    type: string
  ControlPlaneIP:
    description: IP address on the control plane
    type: string
  ControlPlaneNetwork:
    description: Name of the control plane network
    default: ctlplane
    type: string
  PortName:
    description: Name of the port
    default: ''
    type: string
  NetworkName:
    description: # Here for compatability with vip.yaml
    default: ''
    type: string
  FixedIPs:
    description: # Here for compatibility with vip.yaml
    default: []
    type: json
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  IPPool: # Here for compatibility with from_pool.yaml
    default: {}
    description: A network mapped list of IPs
    type: json
  NodeIndex: # Here for compatibility with from_pool.yaml
    default: 0
    description: Index of the IP to get from Pool
    type: number

outputs:
  ip_address:
    description: pass thru network IP
    value: {get_param: ControlPlaneIP}
  ip_address_uri:
    description: pass thru network IP (for compatibility with vip_v6.yaml)
    value: {get_param: ControlPlaneIP}
  ip_subnet:
    description: IP/Subnet CIDR for the pass thru network IP
    value:
          list_join:
            - ''
            - - {get_param: ControlPlaneIP}
              - '/'
              - {get_param: ControlPlaneSubnetCidr}
