heat_template_version: 2015-04-30

description: >
  Creates a port on the storage network.

parameters:
  StorageNetName:
    description: Name of the storage neutron network
    default: storage
    type: string
  PortName:
    description: Name of the port
    default: ''
    type: string
  ControlPlaneIP: # Here for compatability with noop.yaml
    description: IP address on the control plane
    default: ''
    type: string
  IPPool: # Here for compatibility with from_pool.yaml
    default: {}
    type: json
  NodeIndex: # Here for compatibility with from_pool.yaml
    default: 0
    type: number
  NetworkName:
    description: # Here for compatibility with vip.yaml
    default: storage
    type: string

resources:

  StoragePort:
    type: OS::Neutron::Port
    properties:
      network: {get_param: StorageNetName}
      name: {get_param: PortName}
      replacement_policy: AUTO

outputs:
  ip_address:
    description: storage network IP
    value: {get_attr: [StoragePort, fixed_ips, 0, ip_address]}
  ip_address_uri:
    description: storage network IP with brackets suitable for a URL
    value:
          list_join:
          - ''
          - - '['
            - {get_attr: [StoragePort, fixed_ips, 0, ip_address]}
            - ']'
  ip_subnet:
    # FIXME: this assumes a 2 digit subnet CIDR (need more heat functions?)
    description: IP/Subnet CIDR for the storage network IP
    value:
          list_join:
            - ''
            - - {get_attr: [StoragePort, fixed_ips, 0, ip_address]}
              - '/'
              - {get_attr: [StoragePort, subnets, 0, cidr, -2]}
              - {get_attr: [StoragePort, subnets, 0, cidr, -1]}
